name: Deploy

on:
  workflow_run:
    workflows: ["Test"]
    types: [completed, requested]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: echo "DEPLOY CODE HERE"
