---
name: Deploy

on:
  branch:
    workflows:
      - test
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: echo "DEPLOY CODE HERE"
