name: Test

jobs:
  test-lint:
  name: Test & Lint
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test & Lint
      run: docker-compose run --rm app sh -c "python manage.py test && flake8"
